global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/details/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8088']
        labels:
          group: 'production'
